// Framer Motion presets — generated by designlang (motionlang)
// Source: https://notion.so/
// 2026-07-07T23:54:17.978Z
//
//   import { transitions, variants } from './notion.so-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeIn: [0.42, 0, 1, 1], // 157× on page
  custom2: [0.45, 0, 0.55, 1], // 10× on page
  custom3: [0.645, 0.045, 0.355, 1], // 6× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 3× on page
  linear: [0, 0, 1, 1], // 1× on page
  custom6: [0.86, 0, 0.07, 1], // 1× on page
  easeOut: [0, 0, 0.58, 1], // 1× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.075,
  xs: 0.1,
  sm: 0.2,
  md: 0.3,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.2, ease: easings.easeIn },
  fast:  { duration: 0.100, ease: easings.easeIn },
  slow:  { duration: 0.360, ease: easings.easeIn },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.050 } },
  },
  AgentAgentEnterD6zdB: {
    hidden: {},
    show: {
      "translate": ["var(--translate-agent-start)","0px"],
      "transform": ["rotate(var(--rotate-agent-start))","rotate(0deg)"],
      transition: transitions.base,
    },
  },
  AgentAgentTaskEnterZpDY1: {
    hidden: {},
    show: {
      "translate": ["var(--translate-task-start)","var(--translate-task)"],
      "transform": ["rotate(var(--rotate-task-start))","rotate(var(--rotate-task))"],
      transition: transitions.base,
    },
  },
  AgentAgentMarkEnter54wKq: {
    hidden: {},
    show: {
      "translate": ["var(--translate-mark-start)","var(--translate-mark)"],
      "transform": ["rotate(var(--rotate-mark-start))","rotate(var(--rotate-mark))"],
      transition: transitions.base,
    },
  },
  IllustrationsRotateEnterXYlPM: {
    hidden: {},
    show: {
      "transform": ["rotate(var(--rotate-start))","rotate(0deg)"],
      transition: transitions.base,
    },
  },
  HomepageHeroAgentsFadeInHBybG: {
    hidden: {},
    show: {
      "opacity": ["var(--opacity-start)","var(--opacity-end)"],
      transition: transitions.base,
    },
  },
  MarqueeMarqueeFramesWsEH6: {
    hidden: {},
    show: {
      "transform": ["translateX(0px)","translateX(calc(-50% - var(--marquee-item-gap) / 2))"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
